### ISSUE TITLE
After pressing the home button it goes home, but then reopens the app straight away.

### ISSUE THREAD

**Issue by kingsuper195** [RUBBER-ES/RUBBER-ES#1]
When the newly added home button, triggered by the home key, is pressed, it goes home. But then the app reopens automatically

**Comment by kingsuper195** [comment]
While an iframe is open and interactivity is enabled, interactivity with the main project is disabled. Therefore, the mouse position is reported as on the icon, and mouse down is reported as true, when the home page is reopened, and the icon is triggered again. The fix was to wait until the mouse was not down before opening the iframe.

**Comment by mcdurdin** [comment]
👏👏👏
